export const enum TeamStatus {
  ADDED = 'ADDED',

  CASE_SELECTION = 'CASE_SELECTION',

  CASE_SELECTED = 'CASE_SELECTED',

  REGISTRATION = 'REGISTRATION',

  REGISTERED = 'REGISTERED',

  PARTICIPANTS_NEEDED = 'PARTICIPANTS_NEEDED',

  CANCELED = 'CANCELED',
}
